config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'notifications/index'
  # get "/bands/:id/invitation" => 'bands#invitation'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: %i[index show]
  resources :bands do
    member do
      get 'invitation'
      patch 'invitation_update'
      get 'destroy_member'
      delete 'destroy_member_delete'
    end
  end
  resources :notifications, only: %i[index]
  get '/users/sign_out' => 'devise/sessions#destroy'
  root to: 'static_pages#home'
  get 'static_pages/help'
  post 'relationships/participation/:id' => 'relationships#participation'
  post 'relationships/:id'               => 'relationships#update'
  delete 'relationships/:id' => 'relationships#destroy'
end

app/models/band.rb
# frozen_string_literal: true

class Band < ApplicationRecord
  mount_uploader :image, BandImageUploader
  validates :name, presence: true, length: { maximum: 30 }, uniqueness: { case_sensitive: true }
  has_many :relationships, dependent: :destroy
  has_many :users, through: :relationships
  has_many :notifications, dependent: :destroy
  accepts_nested_attributes_for :relationships, allow_destroy: true



  def invitation_notification(invitation_users, current_user)
    invitation_users.each do |v|
      visited_user_id = v[1]['user_id'].to_i
      if visited_user_id == 0 || visited_user_id == current_user.id
        next
      else
        invitation_notification = current_user.active_notifications.new(
          band_id: id,
          visited_id: visited_user_id,
          relationship_id: Relationship.find_by(band_id: id, user_id: visited_user_id).id,
          action: 'invitation',
          # checked: false
        )
        invitation_notification.save if invitation_notification.valid?
      end
    end
  end

  def participated_notification(relationship, current_user) # 参加通知
    user_ids = Relationship.where(band_id: id, permission: true).where.not(user_id: current_user.id).select(:user_id)
    members = User.where(id: user_ids) # 招待を承認済みかつ自分を覗いたバンドメンバーに通知を送る
    members.each do |member|
      participated_notification = current_user.active_notifications.new(
        band_id: id,
        visited_id: member.id,
        relationship_id: relationship.id,
        action: 'participated',
        # cheked: false
      )
      participated_notification.save if participated_notification.valid?
    end
  end
end

app/controllers/bands_controller.rb
# frozen_string_literal: true

class BandsController < ApplicationController
  before_action :authenticate_user!
  def index
    @q = Band.ransack(params[:q])
    @collections = User.pluck(:name, :id).unshift(['募集中', 0])
    @bands = @q.result.includes(:users, :relationships).distinct(true).kaminari_page(params[:page])
  end

    def show
    @band = Band.find(params[:id])
    @members = Relationship.where(band_id: @band.id) # @band.usersだとuser_id:0のレコードを取得できない
    @users = @band.users
    unless @band.users.any? # なにかの不具合でメンバーがいないバンドが出来てしまった場合削除する
      @band.destroy
      redirect_to @band
      flash[:alert] = '何らかの理由によりメンバーが不在になったためバンドを削除しました'
    end
  end

  def new
    @band = Band.new

  end

  def create
    @band = Band.new(band_params)
    if @band.save
      @band.invitation_notification(band_params['relationships_attributes'], current_user)
      redirect_to @band
      flash[:notice] = 'バンドの登録に成功しました'
    else
      flash[:alert] = 'バンドの登録に失敗しました'
      render "new"
    end
  end

  def edit
    @band = Band.find(params[:id])
    are_you_member?(@band, current_user)

  end

  def update
    @band = Band.find(params[:id])
    @band.update(band_params)
    if @band.save
      redirect_to @band
      flash[:notice] = 'バンド情報の編集に成功しました'
    else
      render "edit"
      flash[:alert] = 'バンド情報の編集に失敗しました'
    end
  end


  def invitation
    @collections = User.pluck(:name, :id).unshift(['募集中', 0])
    @band = Band.find(params[:id])
    are_you_member?(@band, current_user)
    @band.users.each do |i|
      @collections.delete([i.name, i.id]) if i.id != 0
    end
  end

  def invitation_update
    @band = Band.find(params[:id])
    @band.update(band_params)
    @band.invitation_notification(band_params['relationships_attributes'], current_user)
    redirect_to @band
    flash[:notice] = '招待に成功しました'
  end

  def destroy_member
    @band = Band.find(params[:id])
    are_you_member?(@band, current_user)
    @members = @band.relationships
  end

  def destroy_member_delete
    @band = Band.find(params[:id])
    if params[:deletes].present?
      checked_data = params[:deletes].values # ここでcheckされたデータを受け取っています。
      Relationship.destroy(checked_data)
        if @band.users.empty?
          @band.destroy
          redirect_to @band
          flash[:notice] = 'メンバーが存在しないためバンドを削除しました'
        else
          redirect_to  @band
          flash[:notice] = 'メンバーの削除に成功しました'
        end
    else
      redirect_to destroy_member_band_path
      flash[:alert] = "削除するメンバーを選択してください"
    end


  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
      redirect_to bands_path
      flash[:notice] = 'バンドの削除に成功しました'
  end

    def are_you_member?(band,current_user)
    unless Relationship.find_by(band_id: band.id, user_id: current_user.id, permission: true).present?
      redirect_to root_path
      flash[:alert] = '権限がありません'
    end
  end



  private

  def band_params
    params.require(:band).permit(
      :name,
      :image,
      :deletes,
      relationships_attributes: %i[
        id
        part
        band_id
        user_id
        permission
        _destroy
      ]
    )
  end
end

app/helpers/bands_helper.rb
# frozen_string_literal: true

module BandsHelper
end

app/views/bands/_relationship_create_fields.html.erb
<% @collections = User.pluck(:name, :id).unshift(['募集中', 0]) %>
<div class = "nested-fields">
  <%=f.label "メンバー名" %>
  <%= f.collection_select :user_id, @collections, :last, :first %>
  <%=f.label "パート" %>
  <%= f.select :part,[["Vo1","Vo1"],["Vo2","Vo2"],["GtVo","GtVo"],["BaVo","BaVo"],["Gt1","Gt1"],["Gt2","Gt2"],["Ba","Ba"],["Dr","Dr"],["Key","Key"],["その他","その他"]], class: "form-control"%>
  <%= link_to_remove_association "メンバーを削除", f ,class:"btn btn-warning btn-remove"%>
</div>

app/views/bands/_relationship_fields.html.erb
<% @collections = User.pluck(:name, :id).unshift(['募集中', 0]) %>
<div class = "nested-fields">
  <%=f.label "メンバー名" %>
  <%= f.collection_select :user_id, @collections, :last, :first %>
  <%=f.label "パート" %>
  <%= f.select :part,[["Vo1","Vo1"],["Vo2","Vo2"],["GtVo","GtVo"],["BaVo","BaVo"],["Gt1","Gt1"],["Gt2","Gt2"],["Ba","Ba"],["Dr","Dr"],["Key","Key"],["その他","その他"]], class: "form-control"%>
  <%= link_to_remove_association "メンバーを削除", f ,class:"btn btn-warning btn-remove"%>
  <%= f.hidden_field :permission, :value => false %>
</div>

app/views/bands/destroy_member.html.erb
<div class="col">
<div class="account-wall">
    <div class="chase-logo">
      <h1 class="text-center login-title top-interval">メンバーを削除する</h1>
      <p class="text-center normal-text ">削除するメンバーを選択してください</p>
    </div>
      <%= form_with url:  destroy_member_delete_band_path, method: :delete, local: true do |f| %>
  <% @members.each do |member| %>

    <% if member.user_id == 0 %>
      <div class="media border">
      <%= image_tag '/assets/offer.png' %>
      <div class="media-body">
      <h5>募集中<%= check_box_tag "deletes[#{member.id}]", member.id %></h5>
      <%= member.part%>
      </div>
      </div>
    <%else%>
        <% user = User.find(member.user_id) if User.find(member.user_id) %>
    <div class="media border">
      <img src=<%= user.image %> alt="" class="img-thumbnail">
      <div class="media-body">
      <h5><%=user.name%><%= check_box_tag "deletes[#{member.id}]", member.id %></h5>
      <%= member.part%>
      </div>
    </div>
    <%end%>



<% end %>
  <div class="row">
  <div class="col"><%= link_to 'キャンセル', @band, class: 'btn btn-info btn-fixed-width' %></div>
  <div class="col"><%= submit_tag "一括削除", class: "btn btn-danger btn-fixed-width" %></div>

  </div>

<% end %>

    </div>
</div>

app/views/bands/edit.html.erb
<% members = Relationship.where(band_id: @band.id).map do |member| %>
<% if member.user_id == 0 %>
<% name = "募集中" %>
<% else%>
<% name = User.find(member.user_id).name%>
<% end%>
<% new_member = member.attributes%>
<% new_member.store("name", name) %>
<% new_member%>
<% end%>

<div class="col label-margin">
  <div class="account-wall">
    <div class="chase-logo">
      <h5 class="text-center login-title top-interval">バンド情報を編集する</h5>
      <p class="text-center normal-text ">必要な情報を入力してください</p>
      <%= render "shared/error_messages"%>
    </div>
  <%= react_component("BandEdit",token: form_authenticity_token, band_id: params[:id], band_name: @band.name, band_image: @band.image, members: members ) %>
  <%= link_to 'キャンセル', @band, class: 'btn btn-info btn-block' %>
  <%= link_to "バンドを削除", @band, method: :delete, data: {confirm: "本当によろしいですか？"}, class: 'btn btn-danger btn-block' %>
</div>
</div>
</div>

app/views/bands/index.html.erb
<div class="top-interval"><h2>バンドをさがす</h2></div>
<div class="index_container">
  <div class="sidebar">
    <div class="sidebar__item">
      <%= search_form_for @q do |f| %>
        <div class=serchBox_m>バンド名<br>
        </div>
        <%= f.search_field :name_cont, class: "form-control"  %>
        <div class=serchBox_m>メンバー<br>
        </div>
        <%= f.collection_select :relationships_user_id_in_all, @collections, :last, :first, {:include_blank => '指定なし'},class: "form-control"  %>
        <div class=serchBox_m>所属パート<br>
        </div>
        <%= f.select :relationships_part_eq,[["指定なし",""],["Vocal","Vocal"],["Guitar&Vocal","Guitar&Vocal"],["Bass&Vocal","Bass&Vocal"],["LeadGuitar","LeadGuitar"],["RhythmGuitar","RhythmGuitar"],["Bass","Bass"],["Drums","Drums"],["Keyboard","Keyboard"],["その他","その他"]], {},class: "form-control"%>
        <p></p>

        <div class="row">
        <div class="col"><%= f.submit class: "serchButton_m btn btn-info btn-block" %></div>
        <div class="col"><%=link_to "作成", new_band_path, class: "btn btn-primary btn-block"%></div>


        </div>

      <%end %>
    </div>
  </div>
  <main class="main">
    <table class="table table-striped table-bordered table-sm">
      <thead>
        <tr>
          <th></th>
          <th><%= sort_link(@q, :name, "バンド名") %></th>
          <th><%= sort_link(@q, :updated_at, "変更日時") %></th>
        </tr>
      </thead>
      <tbody>
        <% @bands.each do |band| %>
          <tr>
          <td width="60">
          <img src=<%= band.image %> alt class = "img-thumbnail">
          </td>
            <td>
              <% if Relationship.where(band_id: band.id).find_by(user_id: 0) %>
                <span class="badge badge-secondary">募集中</span>
              <%end%>
              <%if Relationship.find_by(user_id: current_user.id, band_id: band.id) %>
                <% if Relationship.find_by(user_id: current_user.id, band_id: band.id).permission == false %>
                <span class="badge badge-success">招待中</span>
                <%end %>
              <%end %>
              <%=link_to band.name, band%>
            </td>
            <td width="100"><%=band.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </main>
</div>
<%=paginate @bands %>

app/views/bands/invitation.html.erb
<div class="col label-margin">
  <div class="account-wall">
    <div class="chase-logo">
      <h1 class="text-center login-title top-interval">メンバーを招待する</h1>
      <p class="text-center normal-text ">必要な情報を入力してください</p>
    </div>
  <%= react_component("Invitation",token: form_authenticity_token, band_id: params[:id], collections: @collections ) %>
  <%= link_to 'キャンセル', @band, class: 'btn btn-info btn-block' %>

</div>
</div>
</div>

app/views/bands/new.html.erb
<% @collections = User.pluck(:name, :id).unshift(['募集中', 0]) %>
<div class="col label-margin">
  <div class="account-wall">
    <div class="chase-logo">
      <h1 class="text-center login-title top-interval">バンドを作成する</h1>
      <p class="text-center normal-text ">使いやすいようにバンド名は正式名称で入力してください</p>
      <%= render "shared/error_messages" %>
    </div>
  <%= react_component("BandCreate",token: form_authenticity_token, current_user_id: current_user.id.to_s, collections: @collections) %>
  <%= link_to 'キャンセル', @band, class: 'btn btn-info btn-block' %>
</div>
</div>
</div>
</div>

app/views/bands/show.html.erb
<h5 class="top-interval"><img src=<%= @band.image %> alt class = "img-thumbnail"><%= @band.name %></h5>
<table class="table table-striped table-bordered table-sm">
  <thead >
    <tr>
      <th></th>
      <th>名前</th>
      <th>パート</th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
    <%user=User.find_by(id: member.user_id) %>
      <tr>
      <td width="60">
      <% if member.user_id == 0 %>
        <%= image_tag '/assets/offer.png' %>
      <%else%>
        <img src=<%= user.image %> alt class = "img-thumbnail">
        <%end%>
      </td>
        <td>
          <%if member.user_id == 0 %>
            <span class="badge badge-secondary">募集中</span>
            <%unless @users.any? {|v| v.id.to_i == current_user.id} %>
              <%=link_to "参加する","/relationships/participation/#{member.id}", method: :post, data: {confirm: "本当によろしいですか？"}, class: 'btn btn-primary btn-sm' %>

            <%end %>
          <%else %>
            <%if member.permission == false %>
            <span class="badge badge-success">招待中</span>
              <%=link_to user.name, user%>
              <%if member.user_id == current_user.id %>
                <%=link_to "参加する","/relationships/#{member.id}", method: :post, class: "btn btn-primary btn-sm" %>
                <%=link_to "拒否する","/relationships/#{member.id}", method: :delete, class: "btn btn-danger btn-sm"  %>
              <%end %>
              <%else%>
              <%=link_to user.name, user%>
            <%end %>
          <%end %>
        </td>
        <td><%=member.part %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p></p>
<%=link_to 'バンド一覧へ', bands_path, class: 'btn btn-info btn-block' %>
<%if @users.any? {|v| v.id.to_i == current_user.id} && Relationship.find_by(user_id: current_user.id, band_id: @band.id).permission == true %>
<%=link_to '編集する', edit_band_path, class: 'btn btn-warning btn-block' %>
<%=link_to 'メンバーを招待', invitation_band_path, class: 'btn btn-success btn-block' %>
<%=link_to 'メンバーを削除', destroy_member_band_path, class: 'btn btn-danger btn-block' %>


<% end %>