config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'notifications/index'
  # get "/bands/:id/invitation" => 'bands#invitation'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: %i[index show]
  resources :bands do
    member do
      get 'invitation'
      patch 'invitation_update'
      get 'destroy_member'
      delete 'destroy_member_delete'
    end
  end
  resources :notifications, only: %i[index]
  get '/users/sign_out' => 'devise/sessions#destroy'
  root to: 'static_pages#home'
  get 'static_pages/help'
  post 'relationships/participation/:id' => 'relationships#participation'
  post 'relationships/:id'               => 'relationships#update'
  delete 'relationships/:id' => 'relationships#destroy'
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= bootstrap_alert(key) %>">
    <strong>
      <%= value %>
    </strong>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md">
  <%= link_to "" , root_path, class: "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#toggler-demo"
  aria-controls="toggler-demo" aria-expanded="false" aria-label="Toggle navigation" >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="toggler-demo" >
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item"><%= link_to "プロフィール" ,    current_user, {class: "nav-link"} %></li>
        <%if unchecked_notifications.any? %>
          <li class="nav-item">
          <%= link_to  notifications_path, {class: "nav-link"} do %>
          通知<span class="badge badge-dark"><%=@notifications.count%></span>
          </li>
          <%end%>
        <%else %>
          <li class="nav-item"><%= link_to '通知',  notifications_path, {class: "nav-link"} %></li>
        <%end %>
        <li class="nav-item"><%= link_to "部員",    users_path, {class: "nav-link"} %></li>
        <li class="nav-item"><%= link_to "バンド",    bands_path, {class: "nav-link"}%></li>
        <li class="nav-item"><%= link_to "ログアウト" ,      destroy_user_session_path ,method: :delete, class: "nav-link"%></li>
      <%else %>
        <li class="nav-item"><%= link_to "ログイン",     new_user_session_path, {class: "nav-link"} %></li>
        <li class="nav-item"><%= link_to "ユーザー登録",     new_user_registration_path, {class: "nav-link"} %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>FSCmanager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%#= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application',media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="/assets/application.css" media="all" rel="stylesheet" type="text/css" />
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flashes' %>
    <p></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>